[package]
name = "rust-ogp-image-generate"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
image = "0.23.14"
imageproc = "0.22.0"
rusttype = "0.9.2"
